services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7012
      POSTGRES_DB: e_commerce_microservice_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      microservices_network:
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
        - "8181:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      microservices_network:
    restart: unless-stopped

  mongodb:
    container_name: mongo_container
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: awoke
      MONGO_INITDB_ROOT_PASSWORD: 7012
    volumes:
      - mongo_data:/data/db
    networks:
      microservices_network:
    restart: unless-stopped
  mongo-express:
    container_name: mongo_express_container
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: awoke
      ME_CONFIG_MONGODB_ADMINPASSWORD: 7012
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
    networks:
      microservices_network:
    restart: unless-stopped
  zookeeper:
    container_name: zookeeper_container
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      microservices_network:
    restart: unless-stopped
  kafka:
    container_name: kafka_container
    image: confluentinc/cp-kafka:6.2.0
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      microservices_network:
    restart: unless-stopped


  zipkin:
    container_name: zipkin_container
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      microservices_network:
    restart: unless-stopped


  mail-dev:
    container_name: maildev_container
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      microservices_network:
    restart: unless-stopped


networks:
  microservices_network:
    driver: bridge


volumes:
    postgres_data:
    pgadmin_data:
    mongo_data:
