services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7012
      POSTGRES_DB: e_commerce_microservice_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      microservices_network:
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
        - "8181:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      microservices_network:
    restart: unless-stopped

  mongodb:
    container_name: mongo_container
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: awoke
      MONGO_INITDB_ROOT_PASSWORD: 7012
    volumes:
      - mongo_data:/data/db
    networks:
      microservices_network:
    restart: unless-stopped
  mongo-express:
    container_name: mongo_express_container
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: awoke
      ME_CONFIG_MONGODB_ADMINPASSWORD: 7012
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
    networks:
      microservices_network:
    restart: unless-stopped

  mail-dev:
    container_name: maildev_container
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      microservices_network:
    restart: unless-stopped


networks:
  microservices_network:
    driver: bridge


volumes:
    postgres_data:
    pgadmin_data:
    mongo_data:
