spring:
  config:
        import: optional:configserver:http://localhost:8888
  application:
    name: api-gateway-service
management:
  tracing:
    zipkin:
      enabled: true
      base-url: http://zipkin:9411/
    sampler:
      probability: 1.0

